name: Build HCU Plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and Export OCI Image
        run: |
          docker build -t my-pv-plugin:1.0.0 .
          docker save my-pv-plugin:1.0.0 > my-pv-plugin.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hcu-plugin-package
          path: my-pv-plugin.tar
